# Master itinerary data — single source for both the live page and the PDF.
# status: BOOKED, PAID, OPTIONAL, TODO (still needs booking)

PRETRIP = [
    dict(deadline="Sept 5", action="Place AirTags in all 4 bags", detail="Sling bag, passport cover, backpack, Solgaard Carry-On Closet."),
    dict(deadline="Sept 9", action="Activate eSIM", detail="Sim Local, 150GB, EE network — activate the day before departure to preserve the 30-day window."),
    dict(deadline="Sept 9", action="Charge Garmin Epix 53 fully and pack the charger", detail="Battery life has degraded — bring the charger, don't rely on a single charge lasting the trip."),
    dict(deadline="Sept 11", action="Book The Himalayas Putting Green", detail="18-hole course requires booking ~4 days ahead. Book online at standrewsputtingclub.com/himalayas-putting-book-online for the afternoon of Sept 15, on arrival in St Andrews from Gullane. Address: The Links, St Andrews, Fife KY16 9JD. Phone +44 1334 475196."),
    dict(deadline="Sept 13", action="Book car to King's Cross for the morning of Sept 14", detail="~6:00 AM pickup from Novotel Paddington. For 4 people plus luggage, an Uber XL (or Bolt XL) booked/scheduled the night before is the cheapest reliable option — a standard black cab may not fit 4 people and full luggage in one vehicle. Schedule via the Uber app's 'reserve' feature the night before to lock in a car for that early hour."),
]

DAYS = [
    dict(date="Thursday, September 10", items=[
        dict(time="4:45 AM", title="Uber from home to Eppley Airfield", address="4501 Abbott Dr, Omaha, NE 68110", status="TODO", detail="Leave early enough that nothing about the morning has to be rushed."),
        dict(time="6:20 AM", title="Depart Omaha — Southwest 696 to Phoenix", address="Eppley Airfield (OMA)", conf="No confirmation # on file — check booking email", status="BOOKED", detail="Jamey 11C, Kayla 11B. Jayden/Kealey NOT on this leg. Jamey KTN: TT125NJ93."),
        dict(time="~12:10 PM", title="Reunite in Phoenix", address="Phoenix Sky Harbor, Terminal 4", status="—", detail="Steve and Jean are part of the morning. Jayden and Kealey join by early afternoon."),
        dict(time="4:10 PM", title="Depart Phoenix — American Airlines 194 to London Heathrow", address="Phoenix Sky Harbor, Terminal 4", conf="Conf YIUXWC · Seats 18D, 18E, 18G, 18H", status="BOOKED", detail="All 4 together, Boeing 777-200ER economy. Jamey KTN: TT125NJ93."),
    ]),
    dict(date="Friday, September 11", items=[
        dict(time="~10:30 AM", title="Land London Heathrow", address="Heathrow Airport, Terminal 3, Hounslow TW6 1QG", status="—", detail="UK Border Force, baggage claim, then walk to the Heathrow Express platform."),
        dict(time="Late Morning", title="Heathrow Express to Paddington", address="Heathrow Terminal 3 → London Paddington", conf="Ref ac44e8b6", status="BOOKED", detail="Standard class, ~15–20 minutes. Group discount code 3RDOFF applied."),
        dict(time="Early Afternoon", title="Check in — Novotel London Paddington", address="3 Kingdom St, London W2 6BD", conf="Booking PSBLGLNW", status="BOOKED", detail="Two rooms, right at the station. Request early check-in; Sky Garden bags can be left at the front desk if rooms aren't ready."),
        dict(time="Afternoon", title="Hyde Park & Kensington Gardens", address="Hyde Park, London W2", status="—", detail="An easy, unstructured stroll to work off the flight."),
        dict(time="2:45 PM", title="Sky Garden", address="1 Sky Garden Walk, 20 Fenchurch St, London EC3M 8AF", conf="Free timed-entry — no conf # issued; bring photo ID", status="BOOKED", detail="Free skyline views."),
        dict(time="Evening", title="Dinner near Paddington", address="Possible option: Meet Bros Paddington, 29–31 Craven Rd, London W2 3BX (020 7723 7101)", status="TODO", detail="Asian-Fusion halal steakhouse, short walk from the hotel. Not booked — one option under consideration."),
    ]),
    dict(date="Saturday, September 12 — Kealey's Birthday", items=[
        dict(time="Morning", title="Coffee, then the Tube toward Liverpool Street", address="Harrisons Coffee, 3 Spring Street, London W2 3RA", status="—", detail="Circle/Hammersmith & City or the Elizabeth line toward Bishopsgate."),
        dict(time="10:30 AM", title="Duck & Waffle — Birthday Brunch", address="110 Bishopsgate, London EC2N 4AY (40th floor)", conf="No confirmation # on file — booked by Kealey", status="BOOKED", detail="Weekend Brunch menu."),
        dict(time="Afternoon", title="Explore the city — free time", address="Central London", status="—", detail="No fixed plan."),
        dict(time="2:30–4:50 PM", title="The Book of Mormon", address="Prince of Wales Theatre, Coventry Street, London W1D 6AS", conf="Order TFKRVC7 · Stalls Row K, Seats 23–26", status="BOOKED", detail="Kealey's pick for the birthday show. Tickets are paperless mobile — check email/wallet before leaving the hotel."),
        dict(time="~5:00–6:40 PM", title="BOX Piccadilly — ASU game (OPTIONAL)", address="21-23 Shaftesbury Ave, Piccadilly Circus, London W1D 7EF", status="OPTIONAL", detail="ASU vs. Texas A&M kicks off 5:00 PM London time, right as the show lets out. ~5 min from the theatre, ~10 min from Yauatcha — nearly two hours before dinner. Call ahead to confirm the game will be on screen; Trafalgar Square/St James's is the fallback."),
        dict(time="~5:00 PM", title="Trafalgar Square (OPTIONAL — fallback if not at BOX Piccadilly)", address="Trafalgar Square, London WC2N 5DN", status="OPTIONAL", detail="On foot from the theatre."),
        dict(time="Evening", title="Wander into St James's (OPTIONAL)", address="St James's, London SW1", status="OPTIONAL", detail="Quiet streets, royal parks, far fewer tourists."),
        dict(time="Evening", title="Liberty London (OPTIONAL)", address="Great Marlborough St, London W1B 5AH", status="OPTIONAL", detail="The Tudor-style department store, near Piccadilly Circus."),
        dict(time="7:00 PM", title="Yauatcha Soho — Birthday Dinner", address="15–17 Broadwick St, London W1F 0DL", conf="No confirmation # on file", status="BOOKED", detail="Smart-casual, no sport coat."),
        dict(time="Evening", title="Bakerloo line back to Novotel Paddington", address="—", status="—", detail="Direct, no changes."),
    ]),
    dict(date="Sunday, September 13", items=[
        dict(time="Morning", title="Coffee at Harrisons", address="3 Spring Street, London W2 3RA", status="—", detail=""),
        dict(time="Morning (OPTIONAL)", title="Westminster Abbey — exterior & precinct", address="20 Deans Yd, London SW1P 3PA", status="OPTIONAL", detail="Not booked. If a full interior visit is wanted, book several weeks ahead (~$35/person) — otherwise the exterior/precinct alone is worthwhile."),
        dict(time="If Timing Allows (OPTIONAL)", title="Sunday Parade (Changing the Guard, Sunday version)", address="Buckingham Palace, London SW1A 1AA", status="OPTIONAL", detail="Worth catching in passing — not worth planning the morning around."),
        dict(time="10:00–10:30 AM Entry", title="Churchill War Rooms", address="Clive Steps, King Charles St, London SW1A 2AQ", conf="Order D82WR6TM8", status="BOOKED / PAID", detail="4 adults, £136.00 paid in full. Barcode confirmation required at entry — have it ready on phone or printed."),
        dict(time="Midday", title="Lunch — St James's Park", address="St James's Park, London SW1A", status="TODO", detail="Pick up food nearby, eat in the park."),
        dict(time="2:00 PM", title="Buckingham Palace: Interior Tour with Royal Walking Tour", address="Meets at the Duke of York Column, Waterloo Place, 9 Carlton House Terrace, London SW1Y 5AJ — not at the Palace gates", conf="Ref 1217844259", status="BOOKED / PAID", detail="Arrive by 1:45 PM (15 min early). 4 adults, $286.99 paid (10% discount applied)."),
        dict(time="Afternoon", title="Thames walk east toward Tower Bridge", address="South Bank / Thames path", status="—", detail=""),
        dict(time="Afternoon (OPTIONAL)", title="Thames Speedboat", address="Departs Tower Pier, London EC3N 4EH", status="OPTIONAL", detail="Not booked. Runs hourly; book ahead with a buffer before the 6:45 PM dinner if pursuing."),
        dict(time="Afternoon", title="Tower Bridge — optional interior tour", address="Tower Bridge Rd, London SE1 2UP", status="TODO", detail="Worth touring inside if there's time; not yet booked."),
        dict(time="6:45 PM", title="Aqua Shard — Sunday Roast", address="Level 31, 31 St Thomas St, London SE1 9RY", conf="No confirmation # on file", status="BOOKED", detail="Sport coat evening."),
    ]),
    dict(date="Monday, September 14", items=[
        dict(time="~6:00 AM", title="Pre-booked car to King's Cross", address="Novotel Paddington → King's Cross Station, Euston Rd, London N1 9AL", status="TODO — BOOK BY SEPT 13", detail="Book an Uber XL (or Bolt XL) the night before via the app's 'reserve' feature. Recommended over the Tube for 4 people plus luggage this early."),
        dict(time="7:03 AM", title="LNER First Class to Edinburgh", address="King's Cross → Edinburgh Waverley", conf="Ref 26SNB2K4SZ · Coach L, seats 15–18", status="BOOKED", detail="~4.5 hours, arriving around 11:30 AM. £400.80 total."),
        dict(time="~11:30 AM", title="Arrive Edinburgh Waverley — collect rental car", address="Waverley Bridge, Edinburgh EH1 1BB", conf="Alamo Volvo XC90 — Conf #1497942020", status="BOOKED", detail="$237.08 total, Sept 14–16. Double-check the two duplicate Expedia bookings were cancelled."),
        dict(time="2:00 PM", title="Golf — Musselburgh Old Links (hickory clubs)", address="Balcarres Rd, Musselburgh EH21 7SD", conf="Booked via Dave Hillis (oldlinks@enjoyleisure.com)", status="BOOKED / NOT YET PAID", detail="4 players, whole family, hickory clubs (3 right-handed sets + 1 ladies'). ~£88 total ($114.40), ~£22pp. No formal confirmation number on file."),
        dict(time="Evening", title="Drive to Gullane — check into The Bonnie Badger", address="Main St, Gullane EH31 2AB", conf="Booking DBM78037863774731", status="BOOKED", detail="2 Deluxe Loft Rooms, non-refundable, £538.20. No early coffee/breakfast available — Nespresso machines in-room instead."),
        dict(time="7:00 PM", title="Dinner — The Bonnie Badger, The Stables", address="Main St, Gullane EH31 2AB", conf="Table for 4, confirmed", status="BOOKED", detail="A proper Scottish evening to close out the first day north. Sport coat evening."),
    ]),
    dict(date="Tuesday, September 15", items=[
        dict(time="Sunrise", title="A quiet look at Gullane village and coast", address="Gullane, East Lothian", status="—", detail=""),
        dict(time="8:00 AM", title="Golf — Gullane No. 2", address="East Links Rd, Gullane EH31 2BB", conf="Booking ID 583112", status="BOOKED / PAID", detail="Jamey, Jayden, Kealey playing (£300 total, $390); Kayla walking. Electric trolleys with GPS confirmed. Club hire (£180/$234) and trolley rental (£27/$35.10) due directly to the pro shop on arrival — NOT yet paid. Pick up clubs by 7:00 AM, warm up 7:15 AM. Planning conservatively for a 5-hour round (finish ~1:00 PM) — if shorter, extra flexible time in St Andrews."),
        dict(time="Afternoon", title="Drive to St Andrews (~2 hours)", address="Gullane → St Andrews", status="—", detail="Timing depends on how the golf round runs — no fixed departure."),
        dict(time="Afternoon", title="Fisher & Donaldson — coffee & snack stop", address="13 Church St, St Andrews KY16 9BQ", status="—", detail="Fife-local favorite, known for fudge doughnuts and coffee cream cakes. No reservation."),
        dict(time="Afternoon", title="Old Course, Swilcan Bridge, Cathedral & Castle ruins", address="St Andrews town centre", status="—", detail="All walkable — the compressed version of eight centuries of Scottish golf and history."),
        dict(time="Afternoon", title="The Himalayas Putting Green", address="The Links, St Andrews, Fife KY16 9JD", conf="BOOK ONLINE BY SEPT 11", status="TODO — BOOK BY SEPT 11", detail="18-hole course requires booking ~4 days ahead: standrewsputtingclub.com/himalayas-putting-book-online. Phone +44 1334 475196. No wheeled bags/trolleys allowed on the green."),
        dict(time="Afternoon", title="The R&A World Golf Museum", address="Bruce Embankment, St Andrews KY16 9AB", status="—", detail="Opposite the R&A Clubhouse, steps from the 1st tee."),
        dict(time="Afternoon", title="Clarets — coffee or light bite", address="Inside the R&A World Golf Museum", status="—", detail="Café-brasserie with a view over the Old Course."),
        dict(time="Afternoon", title="Check into Old Course Hotel", address="Old Station Rd, St Andrews KY16 9SP", conf="Bookings 77530SG087104 & 77530SG087105", status="BOOKED", detail="Old Course King Room + Champions Old Course Double Double. Both non-refundable, £660 + £678."),
        dict(time="7:30 PM", title="Road Hole Restaurant", address="Old Course Hotel, Old Station Rd, St Andrews KY16 9SP", conf="Ref BV2WXAKF · 4 guests", status="BOOKED", detail="On-site, overlooking the 17th (Road Hole). Sport coat evening, cufflinks."),
    ]),
    dict(date="Wednesday, September 16", items=[
        dict(time="7:00 AM", title="Road Hole 17th tee photos", address="Old Course, 17th tee, St Andrews", status="—", detail="The 'OLD COURSE HOTEL' aiming-point sign on the railway shed is visible from here."),
        dict(time="8:00 AM", title="Tom Morris Bar & Grill — Breakfast", address="Old Course Hotel, Old Station Rd, St Andrews KY16 9SP", conf="Ref B4GR9JXY", status="BOOKED", detail="On-site, 4 people. Table must be returned by 10:00 AM."),
        dict(time="10:00 AM", title="St Andrews Old Course History Tour", address="Meets near the 1st tee / Old Course, St Andrews", conf="Booking S790-260902-2", status="BOOKED / PAID", detail="4 adults, £80.00 paid via Stripe. Guided walk covering the 1st tee, 18th green, and Swilcan Bridge, ~75–90 min. No ticket needs to be shown on arrival."),
        dict(time="Late Morning", title="More time at St Andrews — Swilcan Bridge, pro shop, R&A Museum", address="St Andrews town centre", status="—", detail="Flexible — however the morning is going determines how long this stretches."),
        dict(time="Afternoon", title="Drive to Edinburgh Waverley — return the rental car", address="St Andrews → Edinburgh Waverley", status="—", detail="Route via M90 / the Cupar junction to skip the bypass and Queensferry Crossing slowdowns."),
        dict(time="4:17 PM", title="LNER South to London", address="Edinburgh Waverley → King's Cross", conf="Coach K, seats 21–24", status="BOOKED", detail="£536.40 total (incl. £40 change fee). Departs 16:17, arrives London ~9:02 PM."),
        dict(time="Evening", title="Check back into Novotel London Paddington", address="3 Kingdom St, London W2 6BD", conf="Booking PSBLGMGV", status="BOOKED", detail=""),
    ]),
    dict(date="Thursday, September 17", items=[
        dict(time="Morning", title="Borough Market", address="8 Southwark St, London SE1 1TL", status="—", detail="Opens 10 AM — best before the crowds. Patrick and Dana Noone joining us."),
        dict(time="Midday", title="Tate Modern", address="Bankside, London SE1 9TG", status="—", detail="Former power station."),
        dict(time="Midday", title="Millennium Bridge → St Paul's Cathedral", address="St Paul's Churchyard, London EC4M 8AD", status="—", detail="Budget 1–1.5 hours. Climb the Dome if energy allows."),
        dict(time="Afternoon", title="West along the South Bank", address="South Bank, London", status="—", detail="Walk or bus."),
        dict(time="3:00 PM", title="The Library at County Hall — Afternoon Tea", address="County Hall, Westminster Bridge Rd, London SE1 7PB", conf="No confirmation # on file", status="BOOKED", detail="Sport coat. Patrick and Dana Noone invited to join."),
        dict(time="Evening (OPTIONAL)", title="London Eye at sunset", address="Riverside Building, County Hall, Westminster Bridge Rd, London SE1 7PB", status="OPTIONAL", detail="Not booked — sunset flights sell out, so book ahead if pursuing this."),
        dict(time="Evening (OPTIONAL)", title="adidas Flagship Store London", address="425 Oxford St, London W1C 2PG", status="OPTIONAL", detail="Patrick & Dana Noone invited. Also on the plan for Sept 18 on the way to Wembley — this is a second, together chance to see it."),
    ]),
    dict(date="Friday, September 18", items=[
        dict(time="Morning", title="Harrods Christmas Shop (4th floor)", address="87–135 Brompton Rd, London SW1X 7XL", status="—", detail=""),
        dict(time="~12:00–12:30 PM", title="adidas Flagship Store London", address="425 Oxford St, London W1C 2PG", status="OPTIONAL", detail="Official Union Jack Classic gear takeover — on the way through, not a special trip. ASU's Adidas Pep Rally (band, spirit squad, Sparky) runs 2:30–4:30 PM at the same store; not staying for it."),
        dict(time="Midday", title="Check out — Novotel London Paddington", address="3 Kingdom St, London W2 6BD", status="—", detail=""),
        dict(time="Midday", title="Tube to Wembley (Bakerloo or Metropolitan/Jubilee)", address="—", status="—", detail=""),
        dict(time="Midday", title="Check into Novotel London Wembley", address="Fulton Rd, Wembley HA9 0TF", conf="Booking PSBLGCBX", status="BOOKED", detail=""),
        dict(time="Afternoon", title="Wembley Stadium Tour", address="Wembley, London HA9 0WS", status="OPTIONAL", detail="Couldn't book a slot in advance. If still interested, try booking once in London or at Wembley itself."),
        dict(time="4:45 PM", title="Sixes Cricket", address="Arena Square, Engineers Way, Wembley HA9 0DH", conf="Ref 69B7TH4GXHBD", status="BOOKED", detail="All 4 player profiles must be registered at sixescricket.com before arrival."),
        dict(time="6:30–8:30 PM", title="The White Horse Wembley", address="Engineers Way, Wembley HA9 0DH (Wembley Park)", conf="Ref DMN-16959678684", status="BOOKED", detail="Conrad family only tonight (4 people) — cashless venue, order at the bar."),
    ]),
    dict(date="Saturday, September 19", items=[
        dict(time="Pregame", title="Feed the Yak", address="Wembley Park area — exact address to confirm", conf="No confirmation # on file", status="BOOKED", detail="6 people, incl. the Noones. Seating time still being finalized."),
        dict(time="60–90 min early", title="Arrive Wembley — security, seats", address="Wembley Stadium, Wembley HA9 0WS", status="—", detail="Doors and security lines move slowly on gameday — arrive early."),
        dict(time="5:00 PM", title="Kickoff — ASU vs. Kansas, Union Jack Classic", address="Wembley Stadium, Wembley HA9 0WS", conf="Order #38-35122/UK8 · Section 124, Row 14, Seats 48-51", status="BOOKED", detail="4 tickets, £825.85 total (incl. facility/service fees) — Christmas 2025 gift, already settled. Patrick and Dana Noone also attending."),
        dict(time="Postgame", title="Walk back to Novotel Wembley", address="Fulton Rd, Wembley HA9 0TF", status="—", detail=""),
    ]),
    dict(date="Sunday, September 20", items=[
        dict(time="Morning", title="Check out of Novotel Wembley", address="Fulton Rd, Wembley HA9 0TF", status="—", detail="No direct Tube from Wembley to Heathrow — plan a car or taxi with a generous buffer."),
        dict(time="4:25 PM", title="Depart Heathrow — American Airlines 195 to Phoenix", address="Heathrow Airport, Terminal 3", conf="Conf YIUXWC · Seats 18D, 18E, 18G, 18H", status="BOOKED", detail="All 4 together. Jamey KTN: TT125NJ93."),
        dict(time="Evening", title="Arrive Phoenix — overnight", address="Phoenix Sky Harbor", status="—", detail="Before the final legs separate."),
    ]),
    dict(date="Monday, September 21", items=[
        dict(time="Morning", title="Southwest 680 — Phoenix to Omaha", address="Phoenix Sky Harbor → Eppley Airfield", conf="No confirmation # on file — check booking email", status="BOOKED", detail="Jamey 8D, Kayla 8E. Jamey KTN: TT125NJ93."),
    ]),
]
